[package]
name = "gui-backup"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
eframe = "0.32.3"
egui = "0.32.3"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.7"
